#!/usr/bin/env zsh

source_if_exists "${HOME}/.config/bspwm/setup_workspaces.sh.local"

bspc config border_width         2
bspc config window_gap           4
bspc config pointer_modifier     mod4	

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config focused_border_color "#6A5ACD"

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

fork_detach ruby-bar.rb
